export const SHANGHAI_POIS = [
  {
    id: "poi-the-bund",
    name: "The Bund",
    chineseName: "外滩",
    latitude: 31.24,
    longitude: 121.49,
    address: "Zhongshan East 1st Road, Huangpu, Shanghai",
    category: "Landmark",
    rating: 4.7,
    imageUrl: "/pois/shanghai-skyline.svg",
    description:
      "A waterfront promenade with classic architecture and views of the Pudong skyline.",
    tags: ["skyline", "night view", "waterfront"],
  },
  {
    id: "poi-yu-garden",
    name: "Yu Garden",
    chineseName: "豫园",
    latitude: 31.2272,
    longitude: 121.4921,
    address: "279 Yuyuan Old Street, Huangpu, Shanghai",
    category: "Garden",
    rating: 4.5,
    imageUrl: "/pois/shanghai-garden.svg",
    description:
      "A historic classical garden with pavilions, rockeries, ponds and nearby traditional streets.",
    tags: ["historic", "garden", "architecture"],
  },
  {
    id: "poi-shanghai-museum",
    name: "Shanghai Museum",
    chineseName: "上海博物馆",
    latitude: 31.2303,
    longitude: 121.47,
    address: "201 People's Avenue, Huangpu, Shanghai",
    category: "Culture",
    rating: 4.6,
    imageUrl: "/pois/shanghai-museum.svg",
    description:
      "A major museum of ancient Chinese art, known for bronzes, ceramics, painting and calligraphy.",
    tags: ["museum", "art", "history"],
  },
  {
    id: "poi-oriental-pearl",
    name: "Oriental Pearl Tower",
    chineseName: "东方明珠",
    latitude: 31.2397,
    longitude: 121.4998,
    address: "1 Century Avenue, Pudong, Shanghai",
    category: "Landmark",
    rating: 4.5,
    imageUrl: "/pois/shanghai-skyline.svg",
    description:
      "An iconic television tower offering observation decks and panoramic views across Shanghai.",
    tags: ["observation deck", "skyline", "family"],
  },
  {
    id: "poi-wukang-mansion",
    name: "Wukang Mansion",
    chineseName: "武康大楼",
    latitude: 31.2026,
    longitude: 121.4387,
    address: "1850 Huaihai Middle Road, Xuhui, Shanghai",
    category: "Landmark",
    rating: 4.6,
    imageUrl: "/pois/shanghai-street.svg",
    description:
      "A celebrated flatiron-style building at the heart of the former French Concession.",
    tags: ["architecture", "photo spot", "city walk"],
  },
  {
    id: "poi-xintiandi",
    name: "Xintiandi",
    chineseName: "新天地",
    latitude: 31.2192,
    longitude: 121.4753,
    address: "Lane 181, Taicang Road, Huangpu, Shanghai",
    category: "Shopping",
    rating: 4.4,
    imageUrl: "/pois/shanghai-street.svg",
    description:
      "A pedestrian district combining restored shikumen houses with cafés, shops and restaurants.",
    tags: ["shopping", "food", "nightlife"],
  },
  {
    id: "poi-tianzifang",
    name: "Tianzifang",
    chineseName: "田子坊",
    latitude: 31.208,
    longitude: 121.468,
    address: "210 Taikang Road, Huangpu, Shanghai",
    category: "Food",
    rating: 4.2,
    imageUrl: "/pois/shanghai-lane.svg",
    description:
      "A maze of narrow lanes filled with small studios, local snacks, cafés and craft shops.",
    tags: ["local food", "lanes", "souvenirs"],
  },
  {
    id: "poi-disneyland",
    name: "Shanghai Disneyland",
    chineseName: "上海迪士尼乐园",
    latitude: 31.1434,
    longitude: 121.657,
    address: "310 Huangzhao Road, Pudong, Shanghai",
    category: "Theme Park",
    rating: 4.7,
    imageUrl: "/pois/shanghai-disney.svg",
    description:
      "A large theme park with immersive lands, family attractions, parades and seasonal shows.",
    tags: ["theme park", "family", "full day"],
  },
];

export const MOCK_TRIPS = [
  {
    id: "trip-shanghai-weekend",
    userId: "user-demo",
    name: "Shanghai Weekend",
    city: "Shanghai",
    startDate: "2026-10-18",
    endDate: "2026-10-19",
  },
  {
    id: "trip-shanghai-five-days",
    userId: "user-demo",
    name: "Shanghai Five-Day Trip",
    city: "Shanghai",
    startDate: "2026-11-03",
    endDate: "2026-11-07",
  },
];

export const MOCK_DAYS = [
  {
    id: "weekend-day-1",
    tripId: "trip-shanghai-weekend",
    date: "2026-10-18",
    dayIndex: 1,
  },
  {
    id: "weekend-day-2",
    tripId: "trip-shanghai-weekend",
    date: "2026-10-19",
    dayIndex: 2,
  },
  {
    id: "five-day-1",
    tripId: "trip-shanghai-five-days",
    date: "2026-11-03",
    dayIndex: 1,
  },
  {
    id: "five-day-2",
    tripId: "trip-shanghai-five-days",
    date: "2026-11-04",
    dayIndex: 2,
  },
  {
    id: "five-day-3",
    tripId: "trip-shanghai-five-days",
    date: "2026-11-05",
    dayIndex: 3,
  },
  {
    id: "five-day-4",
    tripId: "trip-shanghai-five-days",
    date: "2026-11-06",
    dayIndex: 4,
  },
  {
    id: "five-day-5",
    tripId: "trip-shanghai-five-days",
    date: "2026-11-07",
    dayIndex: 5,
  },
];
